using System.Collections.Generic;
using Managers.Settings;
using UnityEditor;
using UnityEditor.Callbacks;
using UnityEngine;
using Utilities;
using Utilities.Files;

namespace Editor
{
    public class PostProcessBuild
    {
        [PostProcessBuild(0)]
        public static void CheckNeedСleanStreamingAssetsFolderPreBuild(BuildTarget target, string path)
        {
            if(!GameSettings.Instance.СleanStreamingAssetsFolderInBuild)
                return;

            if (target == BuildTarget.StandaloneWindows || target == BuildTarget.StandaloneWindows64)
            {
                var pathToBuildFolder = File.GetDirectoryFile(path);
                
                var fullPath = File.PathCombine(pathToBuildFolder, $"{Application.productName}_Data/StreamingAssets");
                File.DeleteFolder(fullPath);
            }else if (target == BuildTarget.StandaloneOSX)
            {
                var fullPath = File.PathCombine(path, $"Contents/Resources/Data/StreamingAssets");
                File.DeleteFolder(fullPath);
            }
        }

        [PostProcessBuild(1)]
        public static void CheckNeedCreateSetuper(BuildTarget target, string path)
        {
            if(!GameSettings.Instance.CreateSetuper)
                return;
            
            if(target == BuildTarget.StandaloneOSX)
                return;

            var architectureBuild = "64";
            if (target == BuildTarget.StandaloneWindows)
                architectureBuild = "32";

            var lines = new List<string>();

            var pathToWindowsFolder = GetPathToWindowsFolder(path);
            var pathToBuildFolder = File.GetDirectoryFile(path);
            var pathToIcon = $"{pathToWindowsFolder}/icon.ico";
            var pathToSave = $"{pathToWindowsFolder}/x{architectureBuild}.iss";

            CheckNeedCreateIcon(pathToIcon);
            
            lines.Add($"; Script generated by the Inno Setup Script Wizard.");
            lines.Add($"; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!");
            lines.Add($"");
            lines.Add($"[Setup]");
            lines.Add($"; NOTE: The value of AppId uniquely identifies this application.");
            lines.Add($"; Do not use the same AppId value in installers for other applications.");
            lines.Add($"; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)");
            lines.Add($"AppId={Application.companyName}_{Application.productName}_{architectureBuild}");
            lines.Add($"AppName={Application.productName}");
            lines.Add($"AppVersion={Application.version}");
            lines.Add($";AppVerName={Application.productName} {Application.version}");
            lines.Add($"AppPublisher={Application.companyName}");
            lines.Add($"DefaultDirName=C:/{Application.companyName}/{Application.productName}");
            lines.Add($"DefaultGroupName={Application.productName}");
            lines.Add($"AllowNoIcons=yes");
            lines.Add($"OutputDir={pathToWindowsFolder}");
            lines.Add($"OutputBaseFilename=setup ({architectureBuild})");
            lines.Add($"SetupIconFile={pathToIcon}");
            lines.Add($"Compression=lzma");
            lines.Add($"SolidCompression=yes");
            lines.Add($"");
            lines.Add($"[Languages]");
            lines.Add($"Name: \"russian\"; MessagesFile: \"compiler:Languages\\Russian.isl\"");
            lines.Add($"");
            lines.Add($"[Tasks]");
            lines.Add($"Name: \"desktopicon\"; Description: \"{{cm:CreateDesktopIcon}}\"; GroupDescription: \"{{cm:AdditionalIcons}}\"; Flags: unchecked");
            lines.Add($"");
            lines.Add($"[Files]");
            lines.Add($"Source: \"{path}\"; DestDir: \"{{app}}\"; Flags: ignoreversion");
            lines.Add($"Source: \"{pathToBuildFolder}/*\"; DestDir: \"{{app}}\"; Flags: ignoreversion recursesubdirs createallsubdirs");
            lines.Add($"; NOTE: Don't use \"Flags: ignoreversion\" on any shared system files");
            lines.Add($"");
            lines.Add($"[Icons]");
            lines.Add($"Name: \"{{group}}\\{Application.productName}\"; Filename: \"{{app}}\\{Application.productName}.exe\"");
            lines.Add($"Name: \"{{commondesktop}}\\{Application.productName}\"; Filename: \"{{app}}\\{Application.productName}.exe\"; Tasks: desktopicon");
            lines.Add($"");
            lines.Add($"[Run]");
            lines.Add($"Filename: \"{{app}}\\{Application.productName}.exe\"; Description: \"{{cm:LaunchProgram,{Application.productName}}}\"; Flags: nowait postinstall skipifsilent");
            
            File.WriteAllLines(pathToSave,lines);
        }

        private static string GetPathToWindowsFolder(string path)
        {
            var pathToArchitectureBuild = File.GetDirectoryFile(path);
            var pathToWindows = File.GetDirectoryFile(pathToArchitectureBuild);
            return pathToWindows;
        }

        private static void CheckNeedCreateIcon(string path)
        {
            if(File.FileExists(path))
                return;

            var pathToPng = File.PathCombine(Application.dataPath, "Images/Icons/256.png");
            var pathToConvert = "C:/tools/ImageMagick-7.1.0-portable-Q16-x64/convert.exe";
            
            string cmd = $"{pathToConvert} \"{pathToPng}\" \"{path}\"";
            
            CommonFunctions.StartProcess(cmd);
        }
        
    }
}